# Generated by Django 4.2.5 on 2023-10-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('count', models.TextField()),
                ('weight', models.TextField()),
                ('name', models.TextField()),
                ('structure', models.TextField()),
                ('image', models.TextField()),
                ('price', models.TextField()),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
