# Generated by Django 4.2.5 on 2023-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('product', models.TextField()),
                ('total_price', models.TextField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
